fieldLayouts:
  5b75e0b3-18a1-4b95-9c76-86645b2bdfbf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74c9ff13-6b1f-4a3a-948c-1a9d2a0f4518
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0532caff-2273-408f-b92d-bd6284d6c308
        userCondition: null
handle: aboutUs
hasTitleField: true
name: About
section: 4be743ac-7093-4d42-9614-856eaf7f590c # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
