fieldLayouts:
  5e3061b3-d7ef-4af7-85b1-a09fd416579c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f9d88e0c-15b1-4fab-91b0-4bba8ffcd4a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63f18369-4d51-4417-9fa2-11e0b810b8c7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20e52328-2569-48fa-aa0f-f4c73e8e3945
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8edb13a2-4a4c-417c-ba9a-7ffbcc94195c # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e879f19a-0281-4bc4-b465-d590ed8e2519
            userCondition: null
            warning: null
            width: 100
        name: 'Front Page'
        uid: af403fff-fa2c-4a0a-8a3e-e83190de5703
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dac413e9-280c-4d5a-b8c9-6b002a7911d0 # Featured Stories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 673ae16a-0a3f-48f9-b1f1-8b943431549d
            userCondition: null
            warning: null
            width: 100
        name: 'Featured Story'
        uid: 43c73cf7-29d3-4654-b3b1-6dd9d71178e6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7dad4d3a-8dd9-482a-acd2-59093cf10f5a # Hosts Intro Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7ead546-a29e-4b26-b0c1-fe9a8dbc9e24
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02d4fede-34e7-489f-a068-098fff61d3f4 # Hosts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24748659-a039-4411-a006-a61bcf27ca7c
            userCondition: null
            warning: null
            width: 100
        name: Hosts
        uid: c83ba8ad-21d1-4494-905f-462f32981eee
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 7d7efc4d-b657-47dc-bb2f-49ec951b8cf0 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
