fieldLayouts:
  8e321f5a-1faf-4b66-a164-8118504188fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c66236e5-a668-467c-9c72-a10d07725b72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03a9628f-a404-4b86-9483-1992dba7dbfc
        userCondition: null
fs: hardDisk
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: hardDisk
transformSubpath: ''
