defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: About
propagationMethod: all
siteSettings:
  0e10cfc2-d5c2-4900-bbdb-75f39e2608b8: # Les Ribaudieres
    enabledByDefault: true
    hasUrls: true
    template: stories/index.twig
    uriFormat: stories
type: single
