defaultPlacement: end
enableVersioning: true
handle: gitesListing
name: 'Gites Listing'
propagationMethod: all
siteSettings:
  0e10cfc2-d5c2-4900-bbdb-75f39e2608b8: # Les Ribaudieres
    enabledByDefault: true
    hasUrls: true
    template: gites/index.twig
    uriFormat: gites
type: single
