defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  0e10cfc2-d5c2-4900-bbdb-75f39e2608b8: # Les Ribaudieres
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry
    uriFormat: 'stories/{slug}'
type: channel
